name: Deploy site to Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        # nim-version: '2.0.0'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build ngen
      run: nimble build -Y
    - name: Generate site
      run: ./ngen
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist