name: Deploy site to Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install libpcre
      run: sudo apt-get install libpcre3-dev libpcre3
    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        # nim-version: '2.0.0'
        repo-token: ${{ secrets.GH_PAT }}
    - name: Nimble Run
      run: nimble run
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./dist